<a href="https://colab.research.google.com/github/karthikoo7/Machine_Learning-BDA-/blob/main/CustomerSegmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('customer_data.csv',encoding='latin1')

In [22]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [23]:
# PreProcessing
print(df.isna().sum())
print(df.shape)

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
(541909, 8)

In [24]:
df.dropna(inplace=True)
df.drop(columns='Description',inplace=True)
print(df.isnull().sum())
print(df.shape)

InvoiceNo      0
StockCode      0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64
(406829, 7)

In [25]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Quantity', 'InvoiceDate', 'UnitPrice',
       'CustomerID', 'Country'],
      dtype='object')

In [26]:
df['Price'] = df['Quantity'] * df['UnitPrice']

In [27]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Quantity', 'InvoiceDate', 'UnitPrice',
       'CustomerID', 'Country', 'Price'],
      dtype='object')

In [36]:
df2 = df.groupby(['InvoiceNo','InvoiceDate','CustomerID'],as_index=False).agg({'Price':'sum'})

The index of your new DataFrame df2 consists of the columns you grouped by: InvoiceNo and InvoiceDate.Because you used .groupby() on these two columns, pandas automatically turned them into a MultiIndex (a hierarchical index) and removed them from the standard columns.

In [37]:
df2.head()

  InvoiceNo     InvoiceDate  CustomerID   Price
0    536365  12/1/2010 8:26     17850.0  139.12
1    536366  12/1/2010 8:28     17850.0   22.20
2    536367  12/1/2010 8:34     13047.0  278.73
3    536368  12/1/2010 8:34     13047.0   70.05
4    536369  12/1/2010 8:35     13047.0   17.85

In [38]:
df2.shape

(22221, 4)

In [41]:
df2 = df2.loc[df2['Price'] > 0,:]
df2.shape

(18562, 4)

In [42]:
# CustomerID , Total No of invoices by that customer, total spent,
# standard deviation of spent in invoice
# days from the last invoice

In [46]:
df3 = df2.groupby(['CustomerID']).agg({'Price':'sum','InvoiceNo':'count','InvoiceDate':'max'})
df3

               Price  InvoiceNo      InvoiceDate
CustomerID
12346.0     77183.60          1  1/18/2011 10:01
12347.0      4310.00          7    8/2/2011 8:48
12348.0      1797.24          4  9/25/2011 13:13
12349.0      1757.55          1  11/21/2011 9:51
12350.0       334.40          1   2/2/2011 16:01
...              ...        ...              ...
18280.0       180.60          1    3/7/2011 9:52
18281.0        80.82          1  6/12/2011 10:53
18282.0       178.05          2   8/5/2011 13:35
18283.0      2094.88         16   9/5/2011 12:35
18287.0      1837.28          3  5/22/2011 10:39

[4338 rows x 3 columns]